---
  - name: Generate firewall-nat-{{inventory_hostname}}.rsc to check and add user
    template: src=nat.rsc.j2 dest={{role_path}}/files/tmp/firewall-nat-{{inventory_hostname}}.rsc
    delegate_to: localhost

  - name: Send firewall-nat-{{inventory_hostname}}.rsc script
    command: scp -P {{ansible_port}} {{role_path}}/files/tmp/firewall-nat-{{inventory_hostname}}.rsc {{ansible_user}}@{{ansible_host}}:/firewall-nat-{{inventory_hostname}}.rsc
    delegate_to: localhost

  - name: Delete temporary firewall-nat-{{inventory_hostname}}.rsc file
    file: path={{role_path}}/files/tmp/firewall-nat-{{inventory_hostname}}.rsc state=absent
    delegate_to: localhost

  - name: Run firewall-nat-{{inventory_hostname}}.rsc on router
    raw: "/import firewall-nat-{{inventory_hostname}}.rsc"
    tags: mikrotik_firewall_services

  - name: Remove firewall-nat-{{inventory_hostname}}.rsc from router
    raw: "/file remove firewall-nat-{{inventory_hostname}}.rsc"
