---
 - hosts: dbserver
   tasks:
   - name: Install MySQL Server and dependencies
     apt: name={{item}} state=latest
     with_items:
       - mysql-server
       - python-mysqldb
   - name: Configure MySQL Server
     template: src=mysqld.conf.j2 dest=/etc/mysql/mysql.conf.d/mysqld.cnf
     register: db_config
   - name: Restart MySQL Server
     when: db_config.changed
     service: name=mysql state=restarted
   - name: Create wordpress database
     mysql_db:
       name: wordpress
       state: present
   - name: Create wordpress user
     mysql_user:
       name: wordpressuser
       host: '%'
       password: wordpresspw
       priv: 'wordpress.*:ALL'
       state: present
   - name: Copy default database dump
     template:
       src: templates/wordpress.sql.j2
       dest: /tmp/wordpress.sql
     register: dump
   - name: Import WordPress dump
     when: dump.changed
     mysql_db:
       name: wordpress
       state: import
       target: /tmp/wordpress.sql
    
 - hosts: webservers
   tasks:
   - name: update
     apt: update_cache=yes
   - name: Installing Apache HTTP Server and dependencies
     apt: name={{item}} state=latest
     with_items:
       - php
       - php-mysql
       - apache2
       - libapache2-mod-php
     register: apache
   - name: disable module mpm_event
     command: a2dismod mpm_event
     when: apache.changed
   - name: enable modules
     command: a2enmod {{item}}
     with_items:
       - mpm_prefork
       - php7.0
     when: apache.changed
   - name: Restart Apache HTTP Server
     when: apache.changed
     service: name=apache2 state=restarted
   - name: Install wordpress files
     git:
       repo: ssh://git@ans1.example.com:/git/portal
       dest: /var/www/html/portal
       version: "{{ app_version }}"
       accept_hostkey: yes
   - name: Configure database connection
     template:
       src: templates/wp-config.php.j2
       dest: /var/www/html/portal/wp-config.php
       owner: www-data
       group: www-data
       mode: 0640

 - hosts: lbalancers
   tasks:
   - name: update
     apt: update_cache=yes
   - name: install nginx
     apt: name={{item}} state=latest
     with_items:
       - nginx
   - name: configure nginx load balancer
     template:
       src: templates/portal.j2
       dest: /etc/nginx/sites-available/portal
     register: nginx_config
   - name: linking wordpress in nginx
     file:
       src: /etc/nginx/sites-available/portal
       dest: /etc/nginx/sites-enabled/portal
       state: link
   - name: Restart Nginx Server
     when: nginx_config.changed
     service: name=nginx state=restarted


